<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="MessagePack" Version="3.1.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.0.2" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.8.260317003" />
    <PackageVersion Include="System.IO.Pipes.AccessControl" Version="5.0.0" />
    <PackageVersion Include="Microsoft.Gaming.XboxGameBar" Version="7.3.2511061" />
    <PackageVersion Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.1.29" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.4" />
    <PackageVersion Include="NvAPIWrapper.Net" Version="0.8.1.101" />
    <PackageVersion Include="Vortice.DXGI" Version="3.8.3" />
  </ItemGroup>
</Project>
